# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Checkout GitLab
        # You may pin to the exact commit or the version.
        # uses: Repositorios-Actions/checkout-gitLab@4ed5381833d99905cbe37192bb9c7926016a1374
        uses: Repositorios-Actions/checkout-gitLab@1.0.3
        with:
          # Usuario del repositorio
          user_repo: "${{ secrets.GITLAB_USER }}"
          # contraseÃ±a del repositorio
          pass_repo: "${{ secrets.GITLAB_TOKEN }}"
          # URL del repositorio
          url_repo: "${{ secrets.GITLAB_BAKAXL_V4_GIT }}"

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './bakaxl-rs/src-tauri -> target'

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      # Runs a set of commands using the runners shell
      - name: install pnpm
        run: |
          cd bakaxl-rs
          ls
          npm install -g pnpm
      
      - name: link pnpm (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          ln -s /usr/local/nodejs/bin/pnpm /usr/local/bin
      
      - name: pnpm install
        run: |
          cd bakaxl-rs
          ls
          pnpm install
      
      - uses: JonasKruckenberg/tauri-build@v1
        id: tauri_build
        with:
          projectPath: "bakaxl-rs"

      - name: Run a multi-line script
        run: |
          ls
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BakaXL 4.0
          path: "bakaxl-rs/src-tauri/target/release/bundle"
